# Generated by Django 4.0.4 on 2022-05-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='targetmiles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
